CREATE AVAILABILITY GROUP [ag1]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
    N'mssql-0.mssql' WITH (
       ENDPOINT_URL = N'tcp://mssql-0.mssql:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC,
       SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
    ),
    N'mssql-1.mssql' WITH ( 
       ENDPOINT_URL = N'tcp://mssql-1.mssql:5022', 
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC,
       SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
    );

ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
