apiVersion: v1
kind: Service
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  ports:
  - port: 1433
    name: ubuntu
  clusterIP: None
  selector:
    app: ubuntu
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ubuntu
spec:
  serviceName: ubuntu
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command: ["/bin/sleep", "3650d"]
        ports:
        - containerPort: 1433
          name: ubuntu
  #       volumeMounts:
  #       - name: www
  #         mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi