FROM ubuntu:20.04       
#ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install apt-utils -y


RUN apt-get install sudo wget curl gnupg gnupg1 gnupg2 -y
RUN apt-get install software-properties-common systemd vim -y
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -


#RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/mssql-server-2019.list)"
RUN add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2022.list)"
RUN apt-get update
RUN apt-get install -y mssql-server

# RUN /opt/mssql/bin/mssql-conf set hadr.hadrenabled  1
# RUN /opt/mssql/bin/mssql-conf set sqlagent.enabled true

EXPOSE 1433 5022

ENTRYPOINT /opt/mssql/bin/sqlservr 





# RUN mkdir var/opt/mssql/sql-server

# # Set default paths
# RUN /opt/mssql/bin/mssql-conf set filelocation.defaultbackupdir /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.defaultdatadir /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.defaultdumpdir /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.defaultlogdir /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.errorlogfile /var/opt/mssql/sql-server/error.log \
#     && /opt/mssql/bin/mssql-conf set filelocation.machinekeyfile /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.masterdatafile /var/opt/mssql/sql-server \
#     && /opt/mssql/bin/mssql-conf set filelocation.masterlogfile /var/opt/mssql/sql-server/master.log
