CREATE AVAILABILITY GROUP [ag1]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
    N'mssql-read-0.mssql-read' WITH (
       ENDPOINT_URL = N'tcp://mssql-read-0.mssql-read:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC,
       SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
    ),
    N'mssql-read-1.mssql-read' WITH ( 
       ENDPOINT_URL = N'tcp://mssql-read-1.mssql-read:5022', 
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC,
       SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
    );

ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
