
CREATE AVAILABILITY GROUP FirstAG
WITH (CLUSTER_TYPE = EXTERNAL)
FOR DATABASE agDB
REPLICA ON N'AGP0'
WITH (
   ENDPOINT_URL = N'TCP://AGP0.FullyQualified.Name:5022',
   FAILOVER_MODE = EXTERNAL,
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
   PRIMARY_ROLE (ALLOW_CONNECTIONS = READ_WRITE, READ_ONLY_ROUTING_LIST = (('AGP1.FullyQualified.Name'))),
   SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL, READ_ONLY_ROUTING_URL = N'TCP://AGP0.FullyQualified.Name:1433')),
N'AGP1' WITH (
   ENDPOINT_URL = N'TCP://AGP1.FullyQualified.Name:5022',
   FAILOVER_MODE = EXTERNAL,
   SEEDING_MODE = AUTOMATIC,
   AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
   PRIMARY_ROLE (ALLOW_CONNECTIONS = READ_WRITE, READ_ONLY_ROUTING_LIST = (('AGP0.FullyQualified.Name'))),
   SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL, READ_ONLY_ROUTING_URL = N'TCP://AGP1.FullyQualified.Name:1433'))

GO