apiVersion: v1
kind: Service
metadata:
  name: mssql-remote
  labels:
    app: mssql-remote
spec:
  type: LoadBalancer
  ports:
  - port: 1433
    name: tcpsql
    targetPort: 1433
  - port: 5022
    name: mirror
    targetPort: 5022
  selector:
    app: mssql-remote
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-remote
spec:
  serviceName: mssql-remote
  replicas: 1
  selector:
    matchLabels:
      app: mssql-remote
  template:
    metadata:
      labels:
        app: mssql-remote
    spec:
      containers:
      - name: mssql-remote
        image: neajmorshad/sql22:0.1 #tasdidur/mssql-rag:pot #mssql-optimized:vtest #msread:v1 #sqlag2020:v1 #mcr.microsoft.com/mssql/server:2019-latest #jrei/systemd-ubuntu:20.04 #ubuntu:20.04 #
        imagePullPolicy: IfNotPresent
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_ENABLE_HADR
            value: "1"
          - name: MSSQL_AGENT_ENABLED
            value: "1"  
          - name: MSSQL_SA_PASSWORD
            value: "Pa55w0rd!"
          - name: MSSQL_PID
            value: "Developer"
        ports:
        - containerPort: 1433
          name: mssql-remote
        - containerPort: 5022
          name: mirror
  #       volumeMounts:
  #       - name: mssql
  #         mountPath: /var/opt/mssql
  # volumeClaimTemplates:
  # - metadata:
  #     name: mssql
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 2Gi
