apiVersion: v1
kind: Service
metadata:
  name: ag2-primary
  namespace: dag
  labels:
    app: ag2-primary
spec:
  type: LoadBalancer
  ports:
    - port: 1433
      name: db
      targetPort: 1433
    - port: 5022
      name: mirror
      targetPort: 5022
  selector:
    role: primary