CREATE AVAILABILITY GROUP [ag1]
    WITH (CLUSTER_TYPE = EXTERNAL)
    FOR REPLICA ON
    N'mssql-read-0' WITH (
       ENDPOINT_URL = N'tcp://mssql-read-0.mssql-read:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = EXTERNAL,
       SEEDING_MODE = AUTOMATIC
    ),
    N'mssql-read-1' WITH ( 
       ENDPOINT_URL = N'tcp://mssql-read-1.mssql-read:5022', 
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = EXTERNAL,
       SEEDING_MODE = AUTOMATIC
    );

ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
