CREATE AVAILABILITY GROUP [ag1]
    WITH (CLUSTER_TYPE = EXTERNAL)
    FOR REPLICA ON
    N'mssql-0' WITH (
       ENDPOINT_URL = N'tcp://mssql-0.mssql:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = EXTERNAL,
       SEEDING_MODE = AUTOMATIC
    ),
    N'mssql-1' WITH ( 
       ENDPOINT_URL = N'tcp://mssql-1.mssql:5022', 
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = EXTERNAL,
       SEEDING_MODE = AUTOMATIC
    );

ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
