CREATE LOGIN node1_Login WITH PASSWORD = 'hello++00A';
CREATE USER node1_User FOR LOGIN node1_Login;
GO


CREATE CERTIFICATE dbm_certificate1
AUTHORIZATION node1_User
FROM FILE = '/var/opt/mssql/data/dbm_certificate1.cer';
GO

GRANT CONNECT ON ENDPOINT::Hadr_endpoint TO node1_Login;



CREATE AVAILABILITY GROUP [ag1]
    WITH (CLUSTER_TYPE = NONE)
    FOR REPLICA ON
    N'node0' WITH (
       ENDPOINT_URL = N'node0:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC
    ),
    N'node1' WITH (
       ENDPOINT_URL = N'node1:5022',
       AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
       FAILOVER_MODE = MANUAL,
       SEEDING_MODE = AUTOMATIC
    );

ALTER AVAILABILITY GROUP [ag1] GRANT CREATE ANY DATABASE;
GO


