apiVersion: v1
kind: Service
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  ports:
  - port: 1433
    name: my-cluster
  - port: 22
    name: scp
  - port: 2224
    name: pm1
  - port: 3121
    name: pm2
  - port: 21064
    name: pm3
  - port: 5405
    protocol: UDP
    name: pm4
  - port: 5022
    name: mirror
  clusterIP: None
  selector:
    app: my-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-cluster
spec:
  serviceName: my-cluster
  replicas: 2
  selector:
    matchLabels:
      app: my-cluster
  template:
    metadata:
      labels:
        app: my-cluster
    spec:
      containers:
      - name: my-cluster
        image: pmk:v14
        imagePullPolicy: IfNotPresent
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: my-cluster_SA_PASSWORD
            value: "Pa55w0rd!"
          - name: my-cluster_PID
            value: "Developer"
          - name: my-cluster_AGENT_ENABLED
            value: "True"
        # command: ["/bin/sh", "/tmp/sc.sh"]
        ports:
        - containerPort: 1433
          name: my-cluster
        - containerPort: 22
          name: scp
        - containerPort: 2224
          name: pm1
        - containerPort: 3121
          name: pm2
        - containerPort: 21064
          name: pm3
        - containerPort: 5405
          protocol: UDP
          name: pm4
        - containerPort: 5022
          name: mirror
        securityContext:
          privileged: true
          runAsGroup: 0
          runAsUser: 0